name: backend
version: 0.1.0.0
license: AGPL-3.0
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at
  <https://github.com/fachpruefungsordnung/fachpruefungsordnung>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - base64-bytestring
  - bytestring
  - Cabal
  - clay
  - containers
  - cryptohash-sha1
  - directory
  - dlist
  - filepath
  - hasql
  - hasql-migration
  - hasql-pool
  - hasql-th
  - hasql-transaction
  - http-api-data
  - http-media
  - http-types
  - insert-ordered-containers
  - jose
  - lens
  - lucid2
  - megaparsec
  - mime-mail
  - mtl
  - network
  - openapi3
  - pandoc-types
  - parser-combinators
  - password
  - pretty-simple
  - process
  - profunctors
  - scientific
  - servant
  - servant-auth-server
  - servant-openapi3
  - servant-server
  - smtp-mail
  - tagged
  - template-haskell
  - temporary
  - text
  - time
  - transformers
  - tuple
  - uuid
  - vector
  - wai
  - wai-app-static
  - warp
  - zip-archive
  - zlib

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  backend-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - backend

tests:
  backend-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - backend
      - servant-client
      - hspec
      - http-client
      - QuickCheck
      - servant-quickcheck
