name: backend
version: 0.1.0.0
license: AGPL-3.0
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at
  <https://github.com/fachpruefungsordnung/fachpruefungsordnung>

dependencies:
  - Cabal
  - base >= 4.7 && < 5
  - insert-ordered-containers
  - scientific
  - smtp-mail
  - mime-mail
  - network
  - tuple
  - lens
  - profunctors
  - containers
  - hasql
  - hasql-th
  - hasql-pool
  - hasql-transaction
  - hasql-migration
  - vector
  - bytestring
  - text
  - zlib
  - cryptohash-sha1
  - containers
  - base64-bytestring
  - time
  - servant
  - servant-server
  - servant-auth-server
  - servant-openapi3
  - openapi3
  - http-api-data
  - tagged
  - wai
  - wai-app-static
  - warp
  - http-types
  - http-media
  - aeson
  - template-haskell
  - filepath
  - directory
  - text
  - dlist
  - lucid2
  - clay
  - zip-archive
  - password
  - jose
  - uuid
  - megaparsec
  - parser-combinators
  - mtl
  - transformers
  - pretty-simple
  - pandoc-types
  - process
  - temporary

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Control.Applicative.Utils
    - Control.Functor.Utils
    - Control.Monad.CollectionState
    - Control.Monad.ConsumableStack
    - Server
    - Parse
    - Mail
    - Docs.FullDocument
    - Docs.Document
    - Docs.Common
    - Docs.Revision
    - Docs.ExampleDoc
    - Docs.Tree
    - Docs.Rendered
    - Docs.Hasql.Transactions
    - Docs.Hasql.Statements
    - Docs.Hasql.Database
    - Docs.Hasql.TreeEdge
    - Docs.Hasql.Sessions
    - Docs.Hash
    - Docs.LTML
    - Docs.MetaTree
    - Docs.DocumentHistory
    - Docs.Database
    - Docs.UserRef
    - Docs.Renderable
    - Docs.TextElement
    - Docs.TreeRevision
    - Docs.TextRevision
    - Docs.Comment
    - Language.Ltml.Parser.DocumentContainer
    - Language.Ltml.Parser.Keyword
    - Language.Ltml.Parser.Label
    - Language.Ltml.Parser.Table
    - Language.Ltml.Parser.Section
    - Language.Ltml.Parser.MiTree
    - Language.Ltml.Parser.Document
    - Language.Ltml.Parser.Paragraph
    - Language.Ltml.Parser.SimpleBlock
    - Language.Ltml.Parser.Text
    - Language.Ltml.Parser.Footnote.Combinators
    - Language.Ltml.Parser.SimpleSection
    - Language.Ltml.Parser.SimpleParagraph
    - Language.Ltml.Parser.Common.Indent
    - Language.Ltml.Parser.Common.Lexeme
    - Language.Ltml.Parser.Common.Combinators
    - Language.Ltml.Parser.Footnote
    - Language.Ltml.Common
    - Language.Ltml.HTML
    - Language.Ltml.Tree
    - Language.Ltml.AST.DocumentContainer
    - Language.Ltml.AST.Label
    - Language.Ltml.AST.Table
    - Language.Ltml.AST.Section
    - Language.Ltml.AST.Document
    - Language.Ltml.AST.AppendixSection
    - Language.Ltml.AST.Paragraph
    - Language.Ltml.AST.SimpleBlock
    - Language.Ltml.AST.Text
    - Language.Ltml.AST.SimpleSection
    - Language.Ltml.AST.SimpleParagraph
    - Language.Ltml.AST.Node
    - Language.Ltml.AST.Footnote
    - Language.Ltml.Tree.Parser.DocumentContainer
    - Language.Ltml.Tree.Parser.Section
    - Language.Ltml.Tree.Parser.Document
    - Language.Ltml.Tree.Parser.AppendixSection
    - Language.Ltml.Tree.ToMeta
    - Language.Ltml.Tree.ToLtml
    - Language.Ltml.Tree.Example.Fpo
    - Language.Ltml.Tree.Parser
    - Language.Ltml.HTML.Common
    - Language.Ltml.HTML.Export
    - Language.Ltml.HTML.Test
    - Language.Ltml.HTML.FormatString
    - Language.Ltml.HTML.Util
    - Language.Ltml.HTML.CSS.Classes
    - Language.Ltml.HTML.CSS.Color
    - Language.Ltml.HTML.CSS.CustomClay
    - Language.Ltml.HTML.CSS.Util
    - Language.Ltml.HTML.References
    - Language.Ltml.HTML.CSS
    - Language.Ltml.Pretty
    - Language.Ltml.ToLaTeX.LaTeXType
    - Language.Ltml.ToLaTeX.PDFGenerator
    - Language.Ltml.ToLaTeX.Format
    - Language.Ltml.ToLaTeX.Testing
    - Language.Ltml.ToLaTeX.GlobalState
    - Language.Ltml.ToLaTeX.Renderer
    - Language.Ltml.ToLaTeX.PreLaTeXType
    - Language.Ltml.ToLaTeX.ToPreLaTeXM
    - Language.Ltml.ToLaTeX.ToLaTeX
    - Language.Ltml.Parser
    - Language.Lsd.ToMetaMap
    - Language.Lsd.AST.Type.DocumentContainer
    - Language.Lsd.AST.Type.Table
    - Language.Lsd.AST.Type.Section
    - Language.Lsd.AST.Type.Document
    - Language.Lsd.AST.Type.AppendixSection
    - Language.Lsd.AST.Type.Paragraph
    - Language.Lsd.AST.Type.SimpleBlock
    - Language.Lsd.AST.Type.Text
    - Language.Lsd.AST.Type.SimpleSection
    - Language.Lsd.AST.Type.Enum
    - Language.Lsd.AST.Type.SimpleParagraph
    - Language.Lsd.AST.Type.Footnote
    - Language.Lsd.AST.Common
    - Language.Lsd.AST.Format
    - Language.Lsd.AST.SimpleRegex
    - Language.Lsd.AST.Type
    - Language.Lsd.Example.Fpo
    - Language.Lsd.Example
    - Database
    - UserManagement.User
    - UserManagement.Transactions
    - UserManagement.DocumentPermission
    - UserManagement.Statements
    - UserManagement.Sessions
    - UserManagement.Group
    - Docs
    - Data.Typography
    - Data.Text.FromWhitespace
    - Data.Map.Utils
    - Logging.Scope
    - Logging.Logs
    - Server.Handlers.AuthHandlers
    - Server.Handlers.PasswordResetHandlers
    - Server.Handlers.UserHandlers
    - Server.Handlers.DocsHandlers
    - Server.Handlers.RoleHandlers
    - Server.Handlers.RenderHandlers
    - Server.Handlers.GroupHandlers
    - Server.Auth.PasswordReset
    - Server.Auth.PasswordResetUtil
    - Server.HTTPHeaders
    - Server.HandlerUtil
    - Server.Auth
    - Server.DTOs.Logs
    - Server.DTOs.Comments
    - Server.DTOs.CreateReply
    - Server.DTOs.CreateTextRevision
    - Server.DTOs.CreateTextElement
    - Server.DTOs.Documents
    - Server.DTOs.CreateDocument
    - Server.DTOs.CreateComment

executables:
  backend-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - backend

tests:
  backend-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - backend
      - servant-client
      - hspec
      - http-client
      - QuickCheck
      - servant-quickcheck
